name: ImportSDKDemo
fileGroups:
  - Configs
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
options:
  postGenCommand: pod install
  bundleIdPrefix: org.mandryl
targets:
  ImportSDKDemo:
    type: application
    platform: iOS
    sources: ImportSDKDemo
    configFiles:
      Debug: Configs/ImportSDKDemo-Debug.xcconfig
      Release: Configs/ImportSDKDemo-Release.xcconfig
    settings:
      CURRENT_PROJECT_VERSION: 1
