name: ImportSDKDemo
fileGroups:
  - Configs
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
targets:
  ImportSDKDemo:
    type: application
    platform: iOS
    sources: ImportSDKDemo
    configFiles:
      Debug: Configs/ImportSDKDemo-Debug.xcconfig
      Release: Configs/ImportSDKDemo-Release.xcconfig
    settings:
      CURRENT_PROJECT_VERSION: 1
    options:
      postGenCommand: pod install
