//
// Incident.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Incidents API Model */
public struct Incident: Codable, Hashable {

    public var objectName: String
    public var region: String

    public init(objectName: String, region: String) {
        self.objectName = objectName
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objectName = "object_name"
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objectName, forKey: .objectName)
        try container.encode(region, forKey: .region)
    }
}

