//
// PostIncidentsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Schema of incident with POST */
public struct PostIncidentsRequest: Codable, Hashable {

    public var imageUrl: String
    public var region: String

    public init(imageUrl: String, region: String) {
        self.imageUrl = imageUrl
        self.region = region
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageUrl
        case region
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(region, forKey: .region)
    }
}

